# -*- coding: utf-8 -*-
"""Ablated_Head_vs_LRR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15p8G41hqt71WRI9z6JVdTIE0Gb2dLOGT
"""

!pip install transformer-lens circuitsvis -q

import torch
import numpy as np
import matplotlib.pyplot as plt
from transformer_lens import HookedTransformer
from collections import Counter
from tqdm import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# Load GPT-2 Small
model = HookedTransformer.from_pretrained(
    "gpt2-small",
    device=device
)

induction_heads = [
    (5, 5),
    (7, 10),
    (5, 1),
    (6, 9),
    (7, 2),
    (5, 0),
    (10, 7),
    (8, 1),
    (10, 1),
    (9, 9)
]

prompts = [


    "The capital of India is",
    "The largest planet in the solar system is",

    "Once upon a time there was",
    "In a distant galaxy humanity discovered",


    "The reason climate change is difficult to solve is",
    "Artificial intelligence may become dangerous if",


    "Alice went to Paris. Bob went to London. Alice went to",
    "The cat sat on the mat. The dog sat on the",

    "The true meaning of life is",
    "Materialistic Wealth is not sufficient"
]

def local_repetition_rate(text, window_size=20):
    words = text.split()

    if len(words) < window_size:
        return 0

    repeated = 0
    total = 0

    for i in range(window_size, len(words)):
        current_word = words[i]

        previous_window = words[i-window_size:i]

        if current_word in previous_window:
            repeated += 1

        total += 1

    return repeated / total if total > 0 else 0

def generate_text(model, prompt, max_new_tokens=100):


    tokens = model.to_tokens(prompt).to(device)


    output_tokens = model.generate(
        tokens,
        max_new_tokens=max_new_tokens,
        temperature=1.0,
        freq_penalty=0.0,
        stop_at_eos=False,
        verbose=False
    )

    text = model.to_string(output_tokens[0])

    return text

def head_ablation_hook(value, hook, heads_to_ablate):
    value = value.clone()

    for head in heads_to_ablate:
        value[:, :, head, :] = 0

    return value

num_heads_list = []

mean_delta_lrrs = []

std_delta_lrrs = []


for n in range(1, len(induction_heads) + 1):

    print(f"\n==============================")
    print(f"Ablating {n} induction heads")
    print(f"==============================")

    heads_subset = induction_heads[:n]

    delta_lrrs = []


    fwd_hooks = []

    for layer, head in heads_subset:

        hook_fn = lambda value, hook, h=head: head_ablation_hook(
            value,
            hook,
            [h]
        )

        fwd_hooks.append(
            (f"blocks.{layer}.attn.hook_z", hook_fn)
        )


    for prompt in tqdm(prompts):

        baseline_text = generate_text(model, prompt)

        baseline_lrr = local_repetition_rate(
            baseline_text
        )


        with model.hooks(fwd_hooks=fwd_hooks):

            ablated_text = generate_text(
                model,
                prompt
            )

        ablated_lrr = local_repetition_rate(
            ablated_text
        )

        delta_lrr = ablated_lrr - baseline_lrr

        delta_lrrs.append(delta_lrr)

    mean_delta = np.mean(delta_lrrs)

    std_delta = np.std(delta_lrrs)

    num_heads_list.append(n)

    mean_delta_lrrs.append(mean_delta)

    std_delta_lrrs.append(std_delta)

    print(f"\nMean ΔLRR: {mean_delta:.4f}")
    print(f"Std ΔLRR : {std_delta:.4f}")

plt.figure(figsize=(8,5))

cmap = plt.cm.viridis

colors = cmap(
    np.linspace(
        0.2,
        0.9,
        len(num_heads_list)
    )
)

for i in range(len(num_heads_list)):

    plt.errorbar(
        num_heads_list[i],
        mean_delta_lrrs[i],
        yerr=std_delta_lrrs[i],
        fmt='o',
        color=colors[i],
        markersize=8,
        capsize=5,
        elinewidth=2
    )

plt.plot(
    num_heads_list,
    mean_delta_lrrs,
    linewidth=2.5,
    color='black',
    alpha=0.8
)

plt.axhline(
    0,
    linestyle='--',
    linewidth=1.5,
    color='gray',
    alpha=0.7
)

plt.xlabel(
    "Number of Induction Heads Ablated",
    fontsize=13
)

plt.ylabel(
    "Mean Δ Local Repetition Rate",
    fontsize=13
)

plt.title(
    "Induction Head Ablation Increases Local Repetition",
    fontsize=15,
    pad=12
)

plt.xticks(fontsize=11)
plt.yticks(fontsize=11)

plt.grid(
    alpha=0.25
)

plt.tight_layout()

plt.show()