# -*- coding: utf-8 -*-
"""Activation_Patching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-1SP-6RamjR5IwvtdXa8wfKrMtBcTvx
"""

!pip install transformer-lens torch

import torch
import numpy as np
from transformer_lens import HookedTransformer
from transformer_lens.patching import generic_activation_patch

device = "cuda" if torch.cuda.is_available() else "cpu"

model = HookedTransformer.from_pretrained(
    "gpt2-small",
    device=device
)

GLOBAL_HEADS = [
    (5,5),
    (7,10),
    (5,1),
    (6,9),
    (7,2),
    (5,0)
]

prompts = [


    "The capital of India is",
    "The largest planet in the solar system is",

    "Once upon a time there was",
    "In a distant galaxy humanity discovered",


    "The reason climate change is difficult to solve is",
    "Artificial intelligence may become dangerous if",


    "Alice went to Paris. Bob went to London. Alice went to",
    "The cat sat on the mat. The dog sat on the",

    "The true meaning of life is",
    "Materialistic Wealth is not sufficient"
]

def token_lrr(tokens, window_size=20):

    seq = tokens.squeeze().tolist()

    if len(seq) < window_size:
        return 0

    repeated = 0
    total = 0

    for i in range(window_size, len(seq)):

        current_token = seq[i]

        previous_window = seq[
            i-window_size:i
        ]

        if current_token in previous_window:
            repeated += 1

        total += 1

    return (
        repeated / total
        if total > 0
        else 0
    )

def get_layer(hook):



    return int(
        hook.name.split(".")[1]
    )


def ablation_hook(z, hook):

    z = z.clone()

    layer = get_layer(hook)

    for L,H in GLOBAL_HEADS:

        if layer == L:
            z[:,:,H,:] = 0

    return z


def patch_hook(clean_cache, prompt_len):

    def hook_fn(z, hook):

        z = z.clone()

        layer = get_layer(hook)

        clean_z = clean_cache[
            hook.name
        ]

        patch_len = min(
            prompt_len,
            z.shape[1],
            clean_z.shape[1]
        )

        for L,H in GLOBAL_HEADS:

            if layer == L:

                z[
                    :,
                    :patch_len,
                    H,
                    :
                ] = clean_z[
                    :,
                    :patch_len,
                    H,
                    :
                ]

        return z

    return hook_fn

recoveries = []

GEN_TOKENS = 100

for prompt in prompts:

    print(
        "\n"
        + "="*60
    )

    print(
        "PROMPT:"
    )

    print(
        prompt
    )

    tokens = (
        model.to_tokens(
            prompt
        )
        .to(device)
    )

    prompt_len = (
        tokens.shape[1]
    )


    model.reset_hooks()

    _, clean_cache = (
        model.run_with_cache(
            tokens
        )
    )

    clean_generated = (
        model.generate(
            tokens,
            max_new_tokens=
            GEN_TOKENS,
            temperature=1.0,
            verbose=False
        )
    )

    clean_lrr = token_lrr(
        clean_generated
    )

    model.reset_hooks()

    used_layers = set(
        layer
        for layer,_
        in GLOBAL_HEADS
    )

    for layer in used_layers:

        model.blocks[
            layer
        ].attn.hook_z.add_hook(
            ablation_hook
        )

    abl_generated = (
        model.generate(
            tokens,
            max_new_tokens=
            GEN_TOKENS,
            temperature=1.0,
            verbose=False
        )
    )

    abl_lrr = token_lrr(
        abl_generated
    )


    model.reset_hooks()

    for layer in used_layers:

        model.blocks[
            layer
        ].attn.hook_z.add_hook(
            ablation_hook
        )

    for layer in used_layers:

        model.blocks[
            layer
        ].attn.hook_z.add_hook(

            patch_hook(
                clean_cache,
                prompt_len
            )

        )

    patched_generated = (
        model.generate(
            tokens,
            max_new_tokens=
            GEN_TOKENS,
            temperature=1.0,
            verbose=False
        )
    )

    patched_lrr = token_lrr(
        patched_generated
    )


    denominator = (
        clean_lrr
        -
        abl_lrr
    )

    if abs(
        denominator
    ) < 1e-8:

        recovery = np.nan

    else:

        recovery = (

            patched_lrr
            -
            abl_lrr

        ) / denominator

    recoveries.append(
        recovery
    )

    print(
        "\nClean LRR:",
        round(
            clean_lrr,
            4
        )
    )

    print(
        "Ablated LRR:",
        round(
            abl_lrr,
            4
        )
    )

    print(
        "Patched LRR:",
        round(
            patched_lrr,
            4
        )
    )

    print(
        "Recovery:",
        round(
            recovery,
            4
        )
    )

model.reset_hooks()

valid = [

    r
    for r in recoveries

    if not np.isnan(r)

]

print(
    "\n"
    + "="*60
)

print(
    "MEAN:",
    np.mean(valid)
)

print(
    "STD:",
    np.std(valid)
)

print(
    "MIN:",
    np.min(valid)
)

print(
    "MAX:",
    np.max(valid)
)