# -*- coding: utf-8 -*-
"""LRR_Entropy_Control Trial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaJma_TH_uqAugr2xaM3uo-vovmqKV5E
"""

!pip install transformer-lens

import torch
from transformer_lens import HookedTransformer

model = HookedTransformer.from_pretrained("gpt2-small")

def make_repeated_tokens(batch=10, seq_len=50, vocab_size=1000):
    half = seq_len // 2
    tokens = torch.randint(0, vocab_size, (batch, half))
    tokens = torch.cat([tokens, tokens], dim=1) # We are essetntially repeating a sequence of tokens
    return tokens

tokens = make_repeated_tokens()

def get_prev_token_pos(tokens):
    batch, seq_len = tokens.shape
    prev_pos = torch.zeros_like(tokens)

    for b in range(batch):
        seen = {}
        for i in range(seq_len):
            tok = tokens[b, i].item()
            if tok in seen:
                prev_pos[b, i] = seen[tok]
            else:
                prev_pos[b, i] = -1
            seen[tok] = i
    return prev_pos

def induction_score(pattern, prev_pos):

    batch, heads, q_len, k_len = pattern.shape

    scores = torch.zeros(heads)

    for h in range(heads):

        total = 0
        count = 0

        for b in range(batch):

            for t in range(q_len):

                p = prev_pos[b, t].item()


                if p == -1:
                    continue


                if p + 1 >= k_len:
                    continue

                total += pattern[b, h, t, p + 1]

                count += 1

        scores[h] = total / (count + 1e-6)

    return scores

tokens = make_repeated_tokens(batch=20, seq_len=50)
logits, cache = model.run_with_cache(tokens)

prev_pos = get_prev_token_pos(tokens)

def get_all_induction_scores(model, cache, prev_pos):
    n_layers = model.cfg.n_layers
    n_heads = model.cfg.n_heads

    scores = torch.zeros(n_layers, n_heads)

    for layer in range(n_layers):
        pattern = cache["pattern", layer]

        scores[layer] = induction_score(pattern, prev_pos)

    return scores

scores = get_all_induction_scores(model, cache, prev_pos)

def print_top_heads(scores, top_k=10):
    flat = []

    for layer in range(scores.shape[0]):
        for head in range(scores.shape[1]):
            flat.append((scores[layer, head].item(), layer, head))

    flat.sort(reverse=True)

    for score, layer, head in flat[:top_k]:
        print(f"Layer {layer}, Head {head}: {score:.4f}")

print_top_heads(scores)

import matplotlib.pyplot as plt

plt.imshow(scores.detach().cpu(), cmap="viridis")
plt.colorbar()
plt.xlabel("Head")
plt.ylabel("Layer")
plt.title("Induction Scores")
plt.show()

heads_to_ablate = [
    (5, 5),
    (7, 10),
    (5, 1),
    (6, 9),
    (7, 2),
    (5, 0)
]

def ablate_heads_hook(z, hook):

    layer = hook.layer()

    for (l, h) in heads_to_ablate:
        if l == layer:
            z[:, :, h, :] = 0

    return z

prompt = 'The capital of India is'

original_logits = model(prompt)

original_next_token = original_logits[0, -1].argmax(dim=-1)
original_text = model.to_string(original_next_token)

print("Original next token:")
print(original_text)

all_fwd_hooks = []
for layer in range(model.cfg.n_layers):
    all_fwd_hooks.append((f"blocks.{layer}.attn.hook_z", ablate_heads_hook))

ablated_logits = model.run_with_hooks(
    prompt,
    fwd_hooks=all_fwd_hooks
)

ablated_next_token = ablated_logits[0, -1].argmax(dim=-1)
ablated_text = model.to_string(ablated_next_token)

print("\nAblated next token:")
print(ablated_text)

original_probs = original_logits[0, -1].softmax(dim=-1)
ablated_probs = ablated_logits[0, -1].softmax(dim=-1)

topk = 10

orig_values, orig_indices = torch.topk(original_probs, topk)
abl_values, abl_indices = torch.topk(ablated_probs, topk)

print("\n=== ORIGINAL TOP TOKENS ===")
for prob, idx in zip(orig_values, orig_indices):
    token = model.to_string(idx)
    print(f"{token!r:15} {prob.item():.4f}")

print("\n=== ABLATED TOP TOKENS ===")
for prob, idx in zip(abl_values, abl_indices):
    token = model.to_string(idx)
    print(f"{token!r:15} {prob.item():.4f}")

from functools import partial

all_fwd_hooks = [
    (f"blocks.{layer}.attn.hook_z", ablate_heads_hook)
    for layer in range(model.cfg.n_layers)
]

with model.hooks(
    fwd_hooks=all_fwd_hooks
):
    ablated_logits, ablated_cache = model.run_with_cache(tokens)

ablated_induction_scores = get_all_induction_scores(
    model,
    ablated_cache,
    prev_pos)

print("Original Model Induction Scores")
print_top_heads(scores)
print('-'*100)
print("Ablated Model Induction Scores")
print_top_heads(ablated_induction_scores)

def predictive_entropy(logits):


    probs = logits.softmax(dim=-1)

    entropy = -(probs * torch.log(probs + 1e-12)).sum(dim=-1)

    return entropy

original_entropy = predictive_entropy(original_logits)

ablated_entropy = predictive_entropy(ablated_logits)

orig_final_entropy = original_entropy[0, -1].item()
abl_final_entropy = ablated_entropy[0, -1].item()

delta_entropy = orig_final_entropy - abl_final_entropy

print("=" * 50)
print("FINAL TOKEN ENTROPY")
print("=" * 50)

print(f"Original Entropy : {orig_final_entropy:.4f}")
print(f"Ablated Entropy  : {abl_final_entropy:.4f}")
print(f"Delta Entropy    : {delta_entropy:.4f}") # Contrary to expectation initially, this is fairly in line with expectation that uncertaintiy increases on abalating induction heads

def single_head_ablation_hook(head_to_ablate):

    def hook_fn(z, hook):

        layer = hook.layer()

        ablate_layer, ablate_head = head_to_ablate

        if layer == ablate_layer:
            z[:, :, ablate_head, :] = 0

        return z

    return hook_fn

def entropy_impact_of_head(head):

    all_hooks = [
        (
            f"blocks.{layer}.attn.hook_z",
            single_head_ablation_hook(head)
        )
        for layer in range(model.cfg.n_layers)
    ]

    ablated_logits = model.run_with_hooks(
        prompt,
        fwd_hooks=all_hooks
    )

    ablated_entropy = predictive_entropy(ablated_logits)

    return (
        original_entropy[0, -1].item()
        -
        ablated_entropy[0, -1].item()
    )

test_heads = [
    (5, 5),
    (7, 10),
    (5, 1),
    (6, 9),
    (7, 2),
    (5, 0)
]

for head in test_heads:

    delta_H = entropy_impact_of_head(head)

    print(f"Head {head}: ΔH = {delta_H:.4f}")

entropy_scores = torch.zeros(
    model.cfg.n_layers,
    model.cfg.n_heads
)

for layer in range(model.cfg.n_layers):

    for head in range(model.cfg.n_heads):

        delta_H = entropy_impact_of_head((layer, head))

        entropy_scores[layer, head] = delta_H

        print(f"Layer {layer} Head {head}: {delta_H:.4f}")

entropy_np = entropy_scores.detach().cpu().numpy()


plt.figure(figsize=(12, 8))

im = plt.imshow(
    entropy_np,
    cmap="coolwarm",
    aspect="auto"
)


cbar = plt.colorbar(im)
cbar.set_label("Δ Entropy", fontsize=12)


plt.xlabel("Attention Head", fontsize=12)
plt.ylabel("Layer", fontsize=12)

plt.title(
    "Entropy Change After Single Head Ablation",
    fontsize=14
)


plt.xticks(range(model.cfg.n_heads))
plt.yticks(range(model.cfg.n_layers))


for layer in range(model.cfg.n_layers):
    for head in range(model.cfg.n_heads):

        value = entropy_np[layer, head]

        plt.text(
            head,
            layer,
            f"{value:.2f}",
            ha="center",
            va="center",
            fontsize=7,
            color="black"
        )

plt.tight_layout()

plt.show()

prompts = [


    "The capital of India is",
    "The largest planet in the solar system is",

    "Once upon a time there was",
    "In a distant galaxy humanity discovered",


    "The reason climate change is difficult to solve is",
    "Artificial intelligence may become dangerous if",


    "Alice went to Paris. Bob went to London. Alice went to",
    "The cat sat on the mat. The dog sat on the",

    "The true meaning of life is",
    "Materialistic Wealth is not sufficient"
]

def generate_text(
    prompt,
    max_new_tokens=100,
    ablate=False
):

    if not ablate:

        output = model.generate(
            prompt,
            max_new_tokens=max_new_tokens,
            temperature=1.0
        )

    else:

        all_fwd_hooks = [
            (
                f"blocks.{layer}.attn.hook_z",
                ablate_heads_hook
            )
            for layer in range(model.cfg.n_layers)
        ]

        with model.hooks(fwd_hooks=all_fwd_hooks):

            output = model.generate(
                prompt,
                max_new_tokens=max_new_tokens,
                temperature=1.0
            )

    return output

def local_repetition_rate(
    tokens,
    window_size=20
):

    repeated = 0
    total = 0

    for i in range(window_size, len(tokens)):

        current = tokens[i]

        window = tokens[i-window_size:i]

        if current in window:
            repeated += 1

        total += 1

    return repeated / max(total, 1)

base_scores = []
ablated_scores = []

for prompt in prompts:


    base_text = generate_text(
        prompt,
        ablate=False
    )

    base_tokens = model.to_tokens(base_text)[0].tolist()

    base_lrr = local_repetition_rate(base_tokens)

    base_scores.append(base_lrr)


    ablated_text = generate_text(
        prompt,
        ablate=True
    )

    ablated_tokens = model.to_tokens(ablated_text)[0].tolist()

    ablated_lrr = local_repetition_rate(ablated_tokens)

    ablated_scores.append(ablated_lrr)



    print("=" * 70)
    print("PROMPT:")
    print(prompt)

    print("\nBASE LOCAL REPETITION:")
    print(f"{base_lrr:.4f}")

    print("\nABLATED LOCAL REPETITION:")
    print(f"{ablated_lrr:.4f}")

    print("\nDELTA:")
    print(f"{ablated_lrr - base_lrr:.4f}")


import numpy as np

mean_base = np.mean(base_scores)
mean_ablated = np.mean(ablated_scores)

print("\n")
print("=" * 70)
print("FINAL RESULTS")
print("=" * 70)

print(f"Mean Base LRR      : {mean_base:.4f}")
print(f"Mean Ablated LRR   : {mean_ablated:.4f}")
print(f"Mean Delta         : {mean_ablated - mean_base:.4f}")

import torch
import matplotlib.pyplot as plt
import numpy as np

def single_head_ablation_hook(head_to_ablate):

    def hook_fn(z, hook):

        layer = hook.layer()

        ablate_layer, ablate_head = head_to_ablate

        if layer == ablate_layer:

            z[:, :, ablate_head, :] = 0

        return z

    return hook_fn

prompt = "In a distant galaxy humanity discovered"

def generate_text_single_head_ablation(
    prompt,
    head_to_ablate,
    max_new_tokens=100
):

    all_fwd_hooks = [
        (
            f"blocks.{layer}.attn.hook_z",
            single_head_ablation_hook(head_to_ablate)
        )
        for layer in range(model.cfg.n_layers)
    ]

    with model.hooks(fwd_hooks=all_fwd_hooks):

        output = model.generate(
            prompt,
            max_new_tokens=max_new_tokens,
            temperature=1.0
        )

    return output

base_text = generate_text(
    prompt,
    ablate=False
)

base_tokens = model.to_tokens(
    base_text
)[0].tolist()

base_lrr = local_repetition_rate(
    base_tokens
)

print("=" * 70)
print("BASELINE")
print("=" * 70)

print("\nGenerated Text:\n")
print(base_text)

print("\nBase Local Repetition Rate:")
print(f"{base_lrr:.4f}")

delta_lrr_scores = torch.zeros(
    model.cfg.n_layers,
    model.cfg.n_heads
)

for layer in range(model.cfg.n_layers):

    for head in range(model.cfg.n_heads):

        ablated_text = generate_text_single_head_ablation(
            prompt,
            head_to_ablate=(layer, head)
        )

        ablated_tokens = model.to_tokens(
            ablated_text
        )[0].tolist()

        ablated_lrr = local_repetition_rate(
            ablated_tokens
        )

        delta_lrr = ablated_lrr - base_lrr

        delta_lrr_scores[layer, head] = delta_lrr


        print(
            f"Layer {layer} Head {head}: "
            f"ΔLRR = {delta_lrr:.4f}"
        )

delta_lrr_np = delta_lrr_scores.detach().cpu().numpy()

plt.figure(figsize=(12, 8))

im = plt.imshow(
    delta_lrr_np,
    cmap="coolwarm",
    aspect="auto"
)

cbar = plt.colorbar(im)

cbar.set_label(
    "Δ Local Repetition Rate",
    fontsize=12
)

plt.xlabel(
    "Attention Head",
    fontsize=12
)

plt.ylabel(
    "Layer",
    fontsize=12
)

plt.title(
    "ΔLRR After Single Head Ablation\n"
    "Prompt: 'In a distant galaxy humanity discovered'",
    fontsize=14
)

plt.xticks(range(model.cfg.n_heads))
plt.yticks(range(model.cfg.n_layers))

for layer in range(model.cfg.n_layers):

    for head in range(model.cfg.n_heads):

        value = delta_lrr_np[layer, head]

        plt.text(
            head,
            layer,
            f"{value:.2f}",
            ha="center",
            va="center",
            fontsize=7,
            color="black"
        )

plt.tight_layout()

plt.show()

prompt = "Once upon a time there was"

base_text = generate_text(
    prompt,
    ablate=False
)

base_tokens = model.to_tokens(
    base_text
)[0].tolist()

base_lrr = local_repetition_rate(
    base_tokens
)

print("=" * 70)
print("BASELINE")
print("=" * 70)

print("\nGenerated Text:\n")
print(base_text)

print("\nBase Local Repetition Rate:")
print(f"{base_lrr:.4f}")

delta_lrr_scores = torch.zeros(
    model.cfg.n_layers,
    model.cfg.n_heads
)

for layer in range(model.cfg.n_layers):

    for head in range(model.cfg.n_heads):

        ablated_text = generate_text_single_head_ablation(
            prompt,
            head_to_ablate=(layer, head)
        )

        ablated_tokens = model.to_tokens(
            ablated_text
        )[0].tolist()

        ablated_lrr = local_repetition_rate(
            ablated_tokens
        )

        delta_lrr = ablated_lrr - base_lrr

        delta_lrr_scores[layer, head] = delta_lrr


        print(
            f"Layer {layer} Head {head}: "
            f"ΔLRR = {delta_lrr:.4f}"
        )

delta_lrr_np = delta_lrr_scores.detach().cpu().numpy()

plt.figure(figsize=(12, 8))

im = plt.imshow(
    delta_lrr_np,
    cmap="coolwarm",
    aspect="auto"
)

cbar = plt.colorbar(im)

cbar.set_label(
    "Δ Local Repetition Rate",
    fontsize=12
)

plt.xlabel(
    "Attention Head",
    fontsize=12
)

plt.ylabel(
    "Layer",
    fontsize=12
)

plt.title(
    "ΔLRR After Single Head Ablation\n"
    "Prompt: 'Once upon a time there was'",
    fontsize=14
)

plt.xticks(range(model.cfg.n_heads))
plt.yticks(range(model.cfg.n_layers))

for layer in range(model.cfg.n_layers):

    for head in range(model.cfg.n_heads):

        value = delta_lrr_np[layer, head]

        plt.text(
            head,
            layer,
            f"{value:.2f}",
            ha="center",
            va="center",
            fontsize=7,
            color="black"
        )

plt.tight_layout()

plt.show()

import random
import numpy as np
import matplotlib.pyplot as plt

induction_heads = [
    (5, 5),
    (7, 10),
    (5, 1),
    (6, 9),
    (7, 2),
    (5, 0)
]

all_heads = []

for layer in range(model.cfg.n_layers):

    for head in range(model.cfg.n_heads):

        all_heads.append((layer, head))

control_pool = [
    head
    for head in all_heads
    if head not in induction_heads
]

def make_ablation_hook(heads_to_ablate):

    def ablation_hook(z, hook):

        layer = hook.layer()

        for (l, h) in heads_to_ablate:

            if l == layer:

                z[:, :, h, :] = 0

        return z

    return ablation_hook

def generate_text_custom_ablation(
    prompt,
    heads_to_ablate,
    max_new_tokens=100
):

    ablation_hook = make_ablation_hook(
        heads_to_ablate
    )

    all_fwd_hooks = [
        (
            f"blocks.{layer}.attn.hook_z",
            ablation_hook
        )
        for layer in range(model.cfg.n_layers)
    ]

    with model.hooks(fwd_hooks=all_fwd_hooks):

        output = model.generate(
            prompt,
            max_new_tokens=max_new_tokens,
            temperature=1.0
        )

    return output

base_scores = []

for prompt in prompts:

    base_text = generate_text(
        prompt,
        ablate=False
    )

    base_tokens = model.to_tokens(
        base_text
    )[0].tolist()

    base_lrr = local_repetition_rate(
        base_tokens
    )

    base_scores.append(base_lrr)

mean_base_lrr = np.mean(base_scores)

print("=" * 70)
print("BASELINE")
print("=" * 70)

print(f"Mean Base LRR: {mean_base_lrr:.4f}")

induction_scores = []

for prompt in prompts:

    ablated_text = generate_text_custom_ablation(
        prompt,
        induction_heads
    )

    ablated_tokens = model.to_tokens(
        ablated_text
    )[0].tolist()

    ablated_lrr = local_repetition_rate(
        ablated_tokens
    )

    induction_scores.append(ablated_lrr)

mean_induction_lrr = np.mean(
    induction_scores
)

delta_induction = (
    mean_induction_lrr
    -
    mean_base_lrr
)

print("\n")
print("=" * 70)
print("INDUCTION HEAD RESULTS")
print("=" * 70)

print(f"Mean Ablated LRR : {mean_induction_lrr:.4f}")
print(f"Delta LRR        : {delta_induction:.4f}")

num_trials = 5

random_delta_lrrs = []

for trial in range(num_trials):


    random_heads = random.sample(
        control_pool,
        len(induction_heads)
    )

    control_scores = []


    for prompt in prompts:

        ablated_text = generate_text_custom_ablation(
            prompt,
            random_heads
        )

        ablated_tokens = model.to_tokens(
            ablated_text
        )[0].tolist()

        ablated_lrr = local_repetition_rate(
            ablated_tokens
        )

        control_scores.append(
            ablated_lrr
        )

    mean_control_lrr = np.mean(
        control_scores
    )

    delta_control = (
        mean_control_lrr
        -
        mean_base_lrr
    )

    random_delta_lrrs.append(
        delta_control
    )

    print("\n")
    print("=" * 70)
    print(f"CONTROL TRIAL {trial+1}")
    print("=" * 70)

    print("Random Heads:")
    print(random_heads)

    print(f"\nMean Ablated LRR : {mean_control_lrr:.4f}")
    print(f"Delta LRR        : {delta_control:.4f}")

print("\n")
print("=" * 70)
print("FINAL COMPARISON")
print("=" * 70)

print(f"Induction Head ΔLRR : {delta_induction:.4f}")

print("\nRandom Control ΔLRRs:")

for i, val in enumerate(random_delta_lrrs):

    print(f"Trial {i+1}: {val:.4f}")

print("\n")

print(
    f"Mean Random Control ΔLRR: "
    f"{np.mean(random_delta_lrrs):.4f}"
)

mean_random = np.mean(random_delta_lrrs)
std_random = np.std(random_delta_lrrs)


labels = [
    "Induction Heads",
    "Random Controls"
]

values = [
    delta_induction,
    mean_random
]

errors = [
    0,
    std_random
]


plt.figure(figsize=(8, 5))

colors = plt.cm.magma(
    np.linspace(0.35, 0.75, 2)
)

bars = plt.bar(
    labels,
    values,
    yerr=errors,
    capsize=8,
    color=colors,
    edgecolor="black",
    linewidth=1.5
)




plt.ylabel(
    "Δ Local Repetition Rate",
    fontsize=12
)

plt.title(
    "Induction Head Ablation Produces Greater\n"
    "Repetition Increase Than Random Head Ablation",
    fontsize=14
)

plt.grid(
    axis="y",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()